version: '2'

services:
  nginx-standalone:
    image: nginx
    container_name: nginx_container
    restart: unless-stopped
    ports:
        - "80:80"
        - "443:443"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./vhost.d:/etc/nginx/vhost.d