version: '2'

services:
  letsencrypt:
    image: blacklabelops/letsencrypt
    container_name: letsencrypt_autorenew
    volumes:
      - letsencrypt_certificates:/etc/letsencrypt
      - letsencrypt_challenges:/var/www/letsencrypt
    environment:
      - 'LETSENCRYPT_DOMAIN1=mario.nellmedina.com'
      - 'LETSENCRYPT_DOMAIN2=jira.nellmedina.com'
      - 'LETSENCRYPT_DOMAIN3=jenkins.nellmedina.com'
      - 'LETSENCRYPT_DOMAIN4=keycloak.nellmedina.com'
      - 'LETSENCRYPT_DOMAIN5=repo.nellmedina.com'
      - 'LETSENCRYPT_DOMAIN6=bitbucket.nellmedina.com'

volumes:
  letsencrypt_certificates:
    external: true
  letsencrypt_challenges:
      external: true