version: '2'

services:
  letsencrypt:
    image: blacklabelops/letsencrypt
    container_name: letsencrypt_install
    ports:
      - '443:443'
    volumes:
      - letsencrypt_certificates:/etc/letsencrypt
    environment:
      - 'LETSENCRYPT_HTTP_ENABLED=false'
      - 'LETSENCRYPT_EMAIL=email@nellmedina.com'
      - 'LETSENCRYPT_DOMAIN1=jira.nellmedina.com'
      - 'LETSENCRYPT_DOMAIN2=jenkins.nellmedina.com'
      - 'LETSENCRYPT_DOMAIN3=keycloak.nellmedina.com'
    command: install

volumes:
  letsencrypt_certificates:
    external: true