version: '2'

services:
  nginx:
    image: blacklabelops/nginx
    container_name: nginx_blacklabel
    restart: unless-stopped
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - letsencrypt_certificates:/etc/letsencrypt
      - letsencrypt_challenges:/var/www/letsencrypt
    environment:
      - 'NGINX_REDIRECT_PORT80=true'
      - 'SERVER1PROXY_APPLICATION=test1'
      - 'SERVER1SERVER_NAME=mario.nellmedina.com'
      - 'SERVER1REVERSE_PROXY_LOCATION1=/'
      - 'SERVER1REVERSE_PROXY_PASS1=http://test1'
      - 'SERVER1HTTPS_ENABLED=true'
      - 'SERVER1HTTP_ENABLED=true'
      - 'SERVER1LETSENCRYPT_CERTIFICATES=true'
      - 'SERVER1CERTIFICATE_FILE=/etc/letsencrypt/live/mario.nellmedina.com/fullchain.pem'
      - 'SERVER1CERTIFICATE_KEY=/etc/letsencrypt/live/mario.nellmedina.com/privkey.pem'
      - 'SERVER1CERTIFICATE_TRUSTED=/etc/letsencrypt/live/mario.nellmedina.com/fullchain.pem'
      - 'SERVER2PROXY_APPLICATION=test2'
      - 'SERVER2SERVER_NAME=jira.nellmedina.com'
      - 'SERVER2REVERSE_PROXY_LOCATION1=/'
      - 'SERVER2REVERSE_PROXY_PASS1=http://test2'
      - 'SERVER2HTTPS_ENABLED=true'
      - 'SERVER2HTTP_ENABLED=true'
      - 'SERVER2LETSENCRYPT_CERTIFICATES=true'
      - 'SERVER2CERTIFICATE_FILE=/etc/letsencrypt/live/mario.nellmedina.com/fullchain.pem'
      - 'SERVER2CERTIFICATE_KEY=/etc/letsencrypt/live/mario.nellmedina.com/privkey.pem'
      - 'SERVER2CERTIFICATE_TRUSTED=/etc/letsencrypt/live/mario.nellmedina.com/fullchain.pem'
  test1:
    image: nginx
    container_name: test1_container
    hostname: test1
    restart: unless-stopped
    volumes:
      - ./test1:/usr/share/nginx/html
  test2:
    image: nginx
    container_name: test2_container
    hostname: test2
    restart: unless-stopped
    volumes:
      - ./test2:/usr/share/nginx/html

volumes:
  letsencrypt_certificates:
    external: true
  letsencrypt_challenges:
    external: true